(function(g){var window=this;var Lxa=function(a,b,c,d){var e=b.dc();g.T(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.bc(c,d?d:"mqdefault.jpg");var k=b instanceof g.ZP?g.cX(b.lengthSeconds):null,l=!!f;f=l&&"RD"==g.WR(f).type;var m=b instanceof g.ZP?b.Ba:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.U("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Hn(c),is_live:m,is_list:l,is_mix:f,background:d?"background-image: url("+
d+")":""};b instanceof g.YR&&(c.playlist_length=b.getLength());a.update(c)},k7=function(a,b){g.$W.call(this,{H:"div",
ca:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.o=a;this.N=!1},l7=function(a){var b={H:"span",
M:"ytp-upnext-top",K:[{H:"span",M:"ytp-upnext-header",K:[g.U("YTP_PLAYLIST_UP_NEXT")]},{H:"span",M:"ytp-upnext-title",K:["{{title}}"]},{H:"span",M:"ytp-upnext-author",K:["{{author}}"]}]},c={href:"{{url}}","aria-label":g.U("YTP_AUTOPLAY_NEXT")};b={H:"div",M:"ytp-upnext",R:{"aria-label":"{{watch}}"},K:[{H:"div",M:"ytp-cued-thumbnail-overlay-image",R:{style:"{{background}}"}},b,{H:"a",M:"ytp-upnext-autoplay-icon",R:c,K:[{H:"svg",R:{height:"100%",version:"1.1",viewBox:"0 0 98 98",width:"100%"},K:[{H:"circle",
M:"ytp-svg-autoplay-circle",R:{cx:"49",cy:"49",fill:"#000","fill-opacity":"0.8",r:"48"}},{H:"circle",M:"ytp-svg-autoplay-ring",R:{cx:"-49",cy:"49","fill-opacity":"0",r:"46.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{H:"polygon",M:"ytp-svg-autoplay-triangle",R:{fill:"#fff",points:"32,27 72,49 32,71"}}]}]},{H:"span",M:"ytp-upnext-bottom",K:[{H:"span",M:"ytp-upnext-cancel"},{H:"span",M:"ytp-upnext-paused",K:[g.U("YTP_AUTOPLAY_PAUSED_3")]}]},
{H:"span",M:"ytp-upnext-close"}]};g.Y.call(this,b);this.B=null;c=this.va["ytp-upnext-cancel"];b=this.va["ytp-upnext-close"];this.B=new g.Y({H:"button",ca:["ytp-upnext-cancel-button","ytp-button"],R:{tabindex:0,"aria-label":g.U("YTP_AUTOPLAY_CANCEL")},K:[g.U("YTP_CANCEL")]});g.M(this,this.B);this.B.U("click",this.hB,this);this.B.Ea(c);c=new g.Y({H:"button",ca:["ytp-upnext-close-button","ytp-button"],R:{"aria-label":g.U("YTP_AUTOPLAY_CANCEL")}});g.M(this,c);c.U("click",this.hB,this);c.Ea(b);this.o=
a;this.J=this.va["ytp-svg-autoplay-ring"];this.F=this.D=this.A=this.C=null;this.G=new g.Ft(this.Zm,5E3,this);g.M(this,this.G);this.I=0;this.P(this.va["ytp-upnext-autoplay-icon"],"click",this.HQ);this.eB();this.P(a,"autonavvisibility",this.eB);this.P(a,"mdxnowautoplaying",this.XP);this.P(a,"mdxautoplaycanceled",this.YP);this.P(a,"mdxautoplayupnext",this.mD);3==this.o.Za()&&(a=(a=g.WV(g.RV(this.o)))?a.cI():null)&&this.mD(a)},Mxa=function(a,b){a.C=b;
Lxa(a,b,g.X(a.o),"hqdefault.jpg")},m7=function(a,b){a.A||(g.KG("a11y-announce",g.U("YTP_PLAYLIST_UP_NEXT")+" "+a.C.title),a.I=(0,g.XG)(),a.A=new g.Ft((0,g.A)(a.sq,a,b),25),a.sq(b));
g.Up(a.element,"ytp-upnext-autoplay-paused")},o7=function(a){n7(a);
a.I=(0,g.XG)();a.sq();g.S(a.element,"ytp-upnext-autoplay-paused")},n7=function(a){a.A&&(a.A.dispose(),a.A=null)},Nxa=function(a){k7.call(this,a,"subscribecard-endscreen");
var b=a.ga();this.A=new g.Y({H:"div",M:"ytp-subscribe-card",K:[{H:"img",M:"ytp-author-image",R:{src:b.profilePicture}},{H:"div",M:"ytp-subscribe-card-right",K:[{H:"div",M:"ytp-author-name",K:[b.author]},{H:"div",M:"html5-subscribe-button-container"}]}]});g.M(this,this.A);this.A.Ea(this.element);this.B=new g.i1(g.U("YTP_SUBSCRIBE"),null,g.U("YTP_UNSUBSCRIBE"),null,!0,!1,b.Sl,b.subscribed,"trailer-endscreen",null,null,a);g.M(this,this.B);this.B.Ea(this.A.va["html5-subscribe-button-container"]);this.hide()},
p7=function(a){var b=g.X(a);
b=b.A&&!b.F;g.Y.call(this,{H:"a",M:"ytp-videowall-still",R:{href:"{{url}}",target:b?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{H:"div",M:"ytp-videowall-still-image",R:{style:"{{background}}"}},{H:"span",M:"ytp-videowall-still-info",K:[{H:"span",M:"ytp-videowall-still-info-bg",K:[{H:"span",M:"ytp-videowall-still-info-content",R:g.rF||g.af?{style:"will-change: opacity"}:void 0,K:[{H:"span",M:"ytp-videowall-still-info-title",
K:["{{title}}"]},{H:"span",M:"ytp-videowall-still-info-author",K:["{{author_and_views}}"]},{H:"span",M:"ytp-videowall-still-info-live",K:[g.U("YTP_LIVE")]},{H:"span",M:"ytp-videowall-still-info-duration",K:["{{duration}}"]}]}]}]},{H:"span",ca:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{H:"span",M:"ytp-videowall-still-listlabel-icon"},g.U("YTP_PLAYLIST"),{H:"span",M:"ytp-videowall-still-listlabel-length",K:[" (",{H:"span",K:["{{playlist_length}}"]},")"]}]},{H:"span",
ca:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{H:"span",M:"ytp-videowall-still-listlabel-mix-icon"},g.U("YTP_MIX"),{H:"span",M:"ytp-videowall-still-listlabel-length",K:[" (50+)"]}]}]});this.B=b;this.o=a;this.A=null;this.U("click",this.C);this.U("keypress",this.D);if(g.X(a).ea){a=a.app.da;b=this.element;g.ib(a.g,b);g.lb(a.g,b);var c=String(a.G++);b.setAttribute("data-visual-id",c);g.We(this,(0,g.A)(a.F,a,b))}},q7=function(a){k7.call(this,a,"videowall-endscreen");
this.ba=a;this.G=0;this.B=[];this.I=this.D=this.C=null;this.J=this.V=!1;this.F=new g.sG(this);g.M(this,this.F);this.L=new g.Ft(g.Aa(g.S,this.element,"ytp-show-tiles"),0);g.M(this,this.L);var b=new g.Y({H:"button",ca:["ytp-button","ytp-endscreen-previous"],R:{"aria-label":g.U("YTP_PREVIOUS")},K:[g.uE()]});g.M(this,b);b.Ea(this.element);b.U("click",this.xM,this);this.O=new g.AW({H:"div",M:"ytp-endscreen-content"});g.M(this,this.O);this.O.Ea(this.element);b=new g.Y({H:"button",ca:["ytp-button","ytp-endscreen-next"],
R:{"aria-label":g.U("YTP_NEXT")},K:[g.vE()]});g.M(this,b);b.Ea(this.element);b.U("click",this.wM,this);this.A=new l7(a);g.M(this,this.A);g.sW(this.o,this.A.element,4);this.hide()},r7=function(a){return g.tW(a.o)&&a.xq()&&!a.I},Oxa=function(a){return(0,g.J)(a.lg,function(a){return g.l_(a)})},Pxa=function(a,b,c){return 0==b&&a.C.length&&2<=c/2&&2<=c/2&&g.X(a.o).experiments.g("video_wall_emphasize_first")?4:2},s7=function(a){var b=a.Us();
b!=a.V&&(a.V=b,a.o.X("autonavvisibility"))},t7=function(a){g.VW.call(this,a);
g.qE({});this.o=null;this.isAvailable=!0;this.A=new g.sG(this);g.M(this,this.A);this.B=g.X(a);Qxa(a)?this.o=new q7(this.g):this.B.ra?this.o=new Nxa(this.g):this.o=new k7(this.g);g.M(this,this.o);g.sW(this.g,this.o.element,4);this.rC();this.A.P(a,"videodatachange",this.rC,this);this.A.P(a,"crn_endscreen",this.ZL,this);this.A.P(a,"crx_endscreen",this.aM,this)},Qxa=function(a){a=g.X(a);
return a.Oc&&!a.ra};g.p(k7,g.$W);k7.prototype.create=function(){this.N=!0};
k7.prototype.destroy=function(){this.N=!1};
k7.prototype.xq=function(){return!1};
k7.prototype.Us=function(){return!1};g.p(l7,g.Y);g.h=l7.prototype;g.h.Zm=function(){this.D&&(this.G.stop(),this.Ca(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.eB=function(){g.GW(this,g.SV(this.o))};
g.h.yQ=function(){window.focus();this.Zm()};
g.h.hide=function(){g.Y.prototype.hide.call(this)};
g.h.sq=function(a){a=a||g.X(this.o).experiments.o("autoplay_time")||1E4;var b=Math.min((0,g.XG)()-this.I,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.o.Za()?this.select(!0):this.A&&this.A.start()};
g.h.select=function(a){a=void 0===a?!1:a;var b=g.X(this.o);if(b.experiments.g("autonav_notifications")&&a&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;g.fW(this.o,"xwebnotifications",{permission:c});"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=this.C.dc(),this.Zm(),this.D=new window.Notification(g.U("YTP_PLAYLIST_UP_NEXT"),{body:c.title,icon:c.bc(b)}),this.F=this.P(this.D,"click",this.yQ),this.G.start())}n7(this);
this.o.Bj(!1,a)};
g.h.HQ=function(a){!g.Nd(this.B.element,g.iG(a))&&g.$Z(a,this.o)&&this.select()};
g.h.hB=function(){g.gW(this.o,"autonavcancel");g.UV(this.o,!0)};
g.h.XP=function(a){this.o.Za();this.show();m7(this,a)};
g.h.mD=function(a){this.o.Za();this.C&&this.C.dc().videoId==a.dc().videoId||Mxa(this,a)};
g.h.YP=function(){this.o.Za();n7(this);this.hide()};
g.h.W=function(){n7(this);this.Zm();g.Y.prototype.W.call(this)};g.p(Nxa,k7);g.p(p7,g.Y);p7.prototype.Rj=function(){var a=this.A.dc().videoId,b=this.A.getPlaylistId();g.U1(this.o.app,a,this.A.Wd,b,void 0,void 0)};
p7.prototype.C=function(a){g.wW(this.o,this.element);g.$Z(a,this.o,this.B,this.A.Wd||void 0)&&this.Rj()};
p7.prototype.D=function(a){switch(a.keyCode){case 13:case 32:g.nG(a)||(this.Rj(),g.pG(a))}};g.p(q7,k7);g.h=q7.prototype;g.h.create=function(){k7.prototype.create.call(this);var a=this.o.ga();a&&(this.C=Oxa(a),this.D=a);this.uh();this.F.P(this.o,"appresize",this.uh);this.F.P(this.o,"videodatachange",this.yM);this.F.P(this.o,"autonavchange",this.cA);this.F.P(this.o,"autonavcancel",this.vM);this.F.P(this.element,"transitionend",this.NR)};
g.h.destroy=function(){g.uG(this.F);g.Ye(this.B);this.B=[];this.C=null;k7.prototype.destroy.call(this);g.Up(this.element,"ytp-show-tiles");this.L.stop()};
g.h.xq=function(){return 1!=this.D.autonavState};
g.h.show=function(){k7.prototype.show.call(this);g.Up(this.element,"ytp-show-tiles");g.X(this.o).isMobile?g.Gt(this.L):this.L.start();(this.J||this.I&&this.I!=this.D.clientPlaybackNonce)&&g.UV(this.o,!1);var a=r7(this);g.tW(this.o)&&g.X(this.o).experiments.g("ui_logging")&&g.fW(this.o,"end",{cancelButtonShow:a?"1":"0",state:this.xq()?"enabled":"disabled"});a?(s7(this),2==this.D.autonavState?g.X(this.o).experiments.g("fast_autonav_in_background")&&3==this.o.lo()?this.A.select(!0):m7(this.A):3==this.D.autonavState&&
o7(this.A)):(g.UV(this.o,!0),s7(this))};
g.h.hide=function(){k7.prototype.hide.call(this);o7(this.A);s7(this)};
g.h.NR=function(a){g.iG(a)==this.element&&this.uh()};
g.h.uh=function(){if(this.C&&this.C.length){g.S(this.element,"ytp-endscreen-paginate");var a=g.Fh(this.element),b=a.width/a.height,c=96/54,d=2,e=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2),n=l*m,q=Pxa(this,0,k),r=Pxa(this,1,k);n+=Math.pow(q,2)-m;n+=Math.pow(r,2)-m;for(n-=m;0<n&&(d<f||e<k);){var w=d/2,z=e/2,B=d<=f-2&&n>=z*m,C=e<=k-2&&n>=w*m;if((w+1)/z*c/b>b/(w/(z+1)*c)&&C)n-=w*m,e+=2;else if(B)n-=z*m,d+=2;else if(C)n-=w*m,e+=2;else break}c=!1;f=2+q;n>=3*m&&
6>=l*m-n&&(e>=f||d>=f)&&2>=r&&(c=!0);m=96*d;n=54*e;b=m/n<b?a.height/n:a.width/m;b=Math.min(b,2);m*=b;n*=b;m*=g.Wc(a.width/m||1,1,1.21);n*=g.Wc(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.O.element;g.Eh(a,m,n);g.mh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});Mxa(this.A,this.C[0]);g.T(this.element,"ytp-endscreen-takeover",r7(this));s7(this);m+=4;n+=4;b=0;f=!1;for(k=0;k<d;k++)for(w=0;w<e;w++)if(z=2<r&&1<=b&&!f?b+1:b,B=0,c&&k>=d-2&&w>=e-2?B=1:0==
w%2&&0==k%2&&(w<q&&k<q?0==w&&0==k&&(B=q):2<r&&w>=e-r&&k>=d-r?w==e-r&&k==d-r&&(f=!0,z=1,B=r):B=2),z=g.Xc(z+this.G,l),0!=B){C=this.B[b];C||(C=new p7(this.o),this.B[b]=C,a.appendChild(C.element));var N=Math.floor(n*w/e),da=Math.floor(m*k/d),Ga=Math.floor(n*(w+B)/e)-N-4,Da=Math.floor(m*(k+B)/d)-da-4;g.th(C.element,da,N);g.Eh(C.element,Da,Ga);g.mh(C.element,"transitionDelay",(w+k)/20+"s");g.T(C.element,"ytp-videowall-still-mini",1==B);g.T(C.element,"ytp-videowall-still-large",2<B);B=C;z=this.C[z];B.A=
z;Lxa(B,z,g.X(B.o),g.Sp(B.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");C=z.Wd;z=B.o;g.X(z).ea&&(z=z.app.da,B=B.element,C=C&&C.itct,N=B.getAttribute("data-visual-id"),g.ib(z.g,B),g.uW(z,"onLogServerVeCreated",{id:N,tracking_params:C}));b++}g.T(this.element,"ytp-endscreen-paginate",b<l);for(d=this.B.length-1;d>=b;d--)e=this.B[d],g.Fd(e.element),g.Xe(e);this.B.length=b}};
g.h.yM=function(){var a=this.o.ga();this.D!=a&&(this.G=0,this.C=Oxa(a),this.D=a,this.uh())};
g.h.wM=function(){this.G+=this.B.length;this.uh()};
g.h.xM=function(){this.G-=this.B.length;this.uh()};
g.h.nK=function(){return!!this.A.A};
g.h.cA=function(a){1==a?(this.J=!1,this.I=this.D.clientPlaybackNonce,n7(this.A),this.g&&this.uh()):(this.J=!0,this.g&&r7(this)&&(2==a?m7(this.A):3==a&&o7(this.A)))};
g.h.vM=function(a){if(a){for(a=0;a<this.B.length;a++)g.xW(this.ba,this.B[a].element,!0);this.cA(1)}else this.I=null,this.J=!1;this.uh()};
g.h.Us=function(){return this.g&&r7(this)};g.p(t7,g.VW);g.h=t7.prototype;g.h.Zz=function(){var a=this.g.ga(),b=!Qxa(this.g)||!(!a.lg||!a.lg.length);a=g.tQ(a,"ypc_module");var c=g.V1(this.g.app);return(b||!1)&&!a&&!c};
g.h.Yz=function(){return this.o.Us()};
g.h.kK=function(){return this.Yz()?this.o.nK():!1};
g.h.W=function(){g.oW(this.g,"endscreen");g.VW.prototype.W.call(this)};
g.h.load=function(){g.VW.prototype.load.call(this);this.o.show();g.X(this.g).ra&&.01>Math.random()&&g.fW(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.VW.prototype.unload.call(this);this.o.hide();this.o.destroy();this.isAvailable=!1};
g.h.ZL=function(a){this.Zz()&&(this.o.N||this.o.create(),"load"==a.getId()&&this.load())};
g.h.aM=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.rC=function(){g.oW(this.g,"endscreen");var a=Math.max(1E3*(this.g.ga().lengthSeconds-10),0);a=new g.TJ(a,0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.TJ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.lW(this.g,[a,b])};g.gX("endscreen",t7);})(_yt_player);
